mysql:
    hostname: localhost
    port: 3306
    database: donationtracker
    user: donationtracker
    password: secret
period: 12000
donationthanks: bc Thanks to PLAYER for donating $AMOUNT to the server!
goals: