name: DonationTracker
main: net.simplycrafted.DonationTracker.DonationTracker
author: Brianetta
version: 0.1
commands:
    donation:
        description: Record a donation by a player
        permission: donationtracker.record
        usage: |
            /<command> <player_name|uuid> <amount>
    donorgoal:
        description: Configure goals for donors
        permission: donationtracker.goals
        usage: |
            /<command> <goal_name>
            /<command> <goal_name> <days> <amount>
            /<command> <goal_name> delete
permissions:
    donationtracker.*:
        description: All DonationTracker permissions
        children:
            donationtracker.record: true
    donationtracker.record:
        description: Can record donations made by players
        default: op
    donationtracker.goals:
        description: Can edit donation goals
        default: op