name: DonationTracker
main: net.simplycrafted.DonationTracker.DonationTracker
author: Brianetta
version: 0.1
commands:
    donation:
        description: Record a donation by a player
        permission: donationtracker.record
        usage: |
            /<command> <player_name|uuid> <amount>
    donorgoal:
        description: Configure goals for donors
        permission: donationtracker.goals
        usage: |
            /<command> <goal_name>
            /<command> <goal_name> days <days>
            /<command> <goal_name> amount <amount>
            /<command> <goal_name> enable <command>
            /<command> <goal_name> disable <command>
            /<command> <goal_name> clear [command]
            /<command> <goal_name> delete
    donationpool:
        description: View donation pool
        permission: donationtracker.poolview
        usage: |
            /<command>
            /<command> <days>
    dgadmin:
        description: Admin commands
        permission: donationtracker.record
        usage: Ask Brian
permissions:
    donationtracker.*:
        description: All DonationTracker permissions
        children:
            donationtracker.record: true
            donationtracker.goals: true
            donationtracker.poolview: true
    donationtracker.record:
        description: Can record donations made by players
        default: op
    donationtracker.goals:
        description: Can edit donation goals
        default: op
    donationtracker.poolview:
        description: Can view the donation pool
        default: true